### ISSUE TITLE
Create Radio Button and Checkbox Elements

### ISSUE THREAD

**Issue by meraghon** [R15-Software-Dev/scholarship-app#40]
Create and design reusable elements for both radio buttons and checkboxes. 
Radio buttons will be used used for Yes/No or other multiple choice questions in both the scholarship provider entry portal and student application form. 
Checkboxes will be used for scholarship providers to select the essays students will need to submit (if any). They'll also be used for selecting grade participation in the student form, in sections such as Athletic Participation, Student Work Experience, Community Involvement, and Extracurricular Activities.

These elements should be able to work with the modal-window element mention in issue #34.

Elements need to be able to keep track of user selections.

**Comment by BobdaFett** [comment]
Closed to restructure project.
