### ISSUE TITLE
Email Validation Script

### ISSUE THREAD

**Issue by meraghon** [R15-Software-Dev/scholarship-app#43]
Create a script that compares the 'Confirm Email Address' input to the 'Contact Email Address' input in the Contact Information section of the scholarship provider entry portal. If the confirmation email address doesn't match, the box will be highlighted in red with an error message below stating that the emails don't match.
This script will ensure that the scholarship provider inputs their email address in correctly.

**Comment by BobdaFett** [comment]
Closed to restructure project.
